### ISSUE TITLE
Usage unclear

### ISSUE THREAD

**Issue by sfrunza13** [IvaniGabrovsky/text-ssg-tool#2]
After installing I used ```node ssg.js -h``` and nothing happened. The console just prompted me for another input.

Afterwards I tried using ```npm start``` wich yielded a result of 

```todos-cli@1.0.0 start C:\Users\stefe\Desktop\IvanCode\todos-cli
> node index.js

Usage: index [options] [command]

Options:
  -h, --help           display help for command

Commands:
  list                 List all the TODO tasks
  add <task>           Add a new TODO task
  mark-done [options]  Mark commands done
  help [command]       display help for command
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! todos-cli@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the todos-cli@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stefe\AppData\Roaming\npm-cache\_logs\2022-09-17T23_34_59_581Z-debug.log
```

I'm not certain what the list of tasks and the mark as done is for. I am assuming this script is a remnant of an older version of the program.

The author of the program in the package.json is someone else's name you might want to change that.

But ssg.js does not seem to work as intended for me after npm install, I will attempt to attach a picture of my console.

![image](https://user-images.githubusercontent.com/77400826/190879817-8c6ef681-0feb-483c-82ab-cd8d67f95251.png)

**Comment by IvaniGabrovsky** [comment]
Missing required parameter input issue has been fixed.
