### ISSUE TITLE
`-v`, `--version`, `-h`, `--help` not working

### ISSUE THREAD

**Issue by SerpentBytes** [IvaniGabrovsky/text-ssg-tool#4]
## Environment Information

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

Running the CLI tool with `-v`, `--version` `-h` `--help` options do not generate any output.

```
todos-cli-fork % node ./ssg.js --version
todos-cli-fork % node ./ssg.js -h       
todos-cli-fork % node ./ssg.js -v
todos-cli-fork % node ./ssg.js --help   
todos-cli-fork % 
```

**Comment by IvaniGabrovsky** [comment]
-h and -v issues have been fixed.
